{{- if .Values.rbac.create -}}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "k8s-pvc-tagger.fullname" . }}
rules:
  - apiGroups:
    - coordination.k8s.io
    resources:
    - leases
    verbs:
    - create
    - get
    - update
{{- if .Values.watchNamespace }}
  - apiGroups:
    - ""
    resources:
    - persistentvolumeclaims
    verbs:
    - get
    - list
    - watch
{{- end }}
{{- if .Values.watchNamespace }}
{{- $ns := split "," .Values.watchNamespace -}}
{{- range $ns }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "k8s-pvc-tagger.fullname" $ }}-pvc
  namespace: {{ . }}
rules:
  - apiGroups:
    - ""
    resources:
    - persistentvolumeclaims
    verbs:
    - get
    - list
    - watch
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "k8s-pvc-tagger.fullname" $ }}-pvc
  namespace: {{ . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "k8s-pvc-tagger.serviceAccountName" $ }}
    namespace: {{ $.Release.Namespace }}
roleRef:
  kind: Role
  name: {{ include "k8s-pvc-tagger.fullname" $ }}-pvc
  apiGroup: rbac.authorization.k8s.io
{{- end }}
{{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "k8s-pvc-tagger.fullname" . }}
rules:
  - apiGroups:
    - ""
    resources:
    - persistentvolumes
{{- if not .Values.watchNamespace }}
    - persistentvolumeclaims
{{- end }}
    verbs:
    - get
    - list
    - watch
{{- if .Values.propagateToPV }}
    - update
{{- end}}
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "k8s-pvc-tagger.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "k8s-pvc-tagger.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "k8s-pvc-tagger.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "k8s-pvc-tagger.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "k8s-pvc-tagger.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ include "k8s-pvc-tagger.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}
