{{- if .Values.serviceMonitor -}}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "k8s-pvc-tagger.fullname" . }}
  namespace: {{ .Values.serviceMonitorNamespace | default .Release.Namespace }}
  labels:
    {{- include "k8s-pvc-tagger.labels" . | nindent 4 }}
    {{- with .Values.serviceMonitorLabels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  endpoints:
  - port: metrics
  jobLabel: jobLabel
  namespaceSelector:
    matchNames:
    - {{ .Release.Namespace }}
  selector:
    matchLabels:
      {{- include "k8s-pvc-tagger.selectorLabels" . | nindent 6 }}
{{- end -}}
