apiVersion: v1
kind: Service
metadata:
  name: {{ include "k8s-pvc-tagger.fullname" . }}
  labels:
    {{- include "k8s-pvc-tagger.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 8000
    targetPort: http
  - name: metrics
    port: 8001
    targetPort: metrics
  selector:
    {{- include "k8s-pvc-tagger.selectorLabels" . | nindent 4 }}
